language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqca2-dev

script:
  - qmake && make && ln -s ../../qca-plugin-stribog.so tests/crypto/qca-plugin-stribog.so && cd tests && qmake && make && ./tst_stribog
